TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: -0.4
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0

  holonomic_robot: false

  yaw_goal_tolerance: 4
  xy_goal_tolerance: 0.2
