global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  static_map: true
  rolling_window: false
  width: 200.0
  height: 200.0
  resolution: 0.05

global_planner:
  cost_factor: 0.55